#!/bin/bash
# vim :set ts=4 sw=4 sts=4

set -e

if [ -f ${OPENSHIFT_REPO_DIR}requirements_openshift.txt ]
then
	cat ${OPENSHIFT_REPO_DIR}requirements_openshift.txt >> ${OPENSHIFT_REPO_DIR}requirements.txt
fi

VIRTENV_VERSION=$(virtual_env_version)
VIRTENV_BASE_DIR=${OPENSHIFT_DATA_DIR}virtualenvs/
VIRTENV_APP_DIR=${VIRTENV_BASE_DIR}${VIRTENV_VERSION}

function install_virtenv() {
    rm -rf ${VIRTENV_BASE_DIR}*

    msg "Création de l'environnement '${VIRTENV_APP_DIR}'..."
    virtualenv ${VIRTENV_APP_DIR} -p ${PYTHON_BIN}

    msg "Chargement de l'environnement '${VIRTENV_APP_DIR}'..."
    source ${VIRTENV_APP_DIR}/bin/activate

    msg "Installation des dépendances de l'application"
    export PIP_DOWNLOAD_CACHE=${OPENSHIFT_TMP_DIR}.pip/cache
    pip install --log=${OPENSHIFT_TMP_DIR}.pip/pip.log -r ${OPENSHIFT_REPO_DIR}requirements.txt
}

function check_virtenv() {
    if [ ! -e "${PYTHON_BIN}" ]
    then
        msg "L'executable python '${PYTHON_BIN}' n'est pas accessible"
        exit 1
    fi

    if [ ! -d "${VIRTENV_BASE_DIR}" ]
    then
        mkdir "${VIRTENV_BASE_DIR}"
    fi

    if [ ! -d "${VIRTENV_APP_DIR}" ]
    then
        msg "L'environnement '${VIRTENV_APP_DIR}' n'existe pas"
        install_virtenv
    fi

    msg "Chargement de l'environnement '${VIRTENV_APP_DIR}'..."
    source ${VIRTENV_APP_DIR}/bin/activate
}

