#!/bin/bash
# vim :set ts=4 sw=4 sts=4

set -e

function msg() {
	echo "*** $@"
}

export OPENSHIFT_RUNTIME_DIR=${OPENSHIFT_HOMEDIR}/diy-0.1/runtime/
export OPENSHIFT_RUN_DIR=${OPENSHIFT_HOMEDIR}/diy-0.1/run/
export OPENSHIFT_LOG_DIR=${OPENSHIFT_DIY_LOG_DIR}
export OPENSHIFT_BIN=${OPENSHIFT_RUNTIME_DIR}/bin/

