#!/bin/bash
# vim :set ts=4 sw=4 sts=4

set -e

function msg() {
	echo "*** $@"
}

export OPENSHIFT_RUNTIME_DIR=${OPENSHIFT_HOMEDIR}diy/runtime/
export OPENSHIFT_LOG_DIR=${OPENSHIFT_DIY_LOG_DIR}
export OPENSHIFT_BIN=${OPENSHIFT_RUNTIME_DIR}bin/

