#!/bin/bash
# vim :set ts=4 sw=4 sts=4

set -e

source ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/common

BUILD_DIR=${OPENSHIFT_TMP_DIR}build/
NGINX_DIR=${OPENSHIFT_RUNTIME_DIR}nginx/
TEMPLATE_DIR=${OPENSHIFT_REPO_DIR}.openshift/templates/

umask 027

mkdir -p ${BUILD_DIR}

msg "Création du fichier de configuration pour nginx..."
cp ${TEMPLATE_DIR}nginx.conf.template ${BUILD_DIR}nginx.conf
perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' ${BUILD_DIR}nginx.conf
cp ${BUILD_DIR}nginx.conf ${NGINX_DIR}conf/nginx.conf

rm -rf ${BUILD_DIR}

VIRTENV_VERSION=$(md5sum ${OPENSHIFT_REPO_DIR}requirements.txt | cut -d ' ' -f1)
VIRTENV_BASE_DIR=${OPENSHIFT_DATA_DIR}virtualenvs/
VIRTENV_APP_DIR=${VIRTENV_BASE_DIR}${VIRTENV_VERSION}

msg "Chargement de l'environnement '${VIRTENV_APP_DIR}'..."
source ${VIRTENV_APP_DIR}/bin/activate

# update openshift.settings python module to provide default application settings module name
pushd ${OPENSHIFT_REPO_DIR} >/dev/null
DEFAULT_SETTINGS=$(find -type f -name 'settings.py' | grep -v '/openshift/' | sed 's/^\.\///')
RESULT=$(echo "${DEFAULT_SETTINGS}" | wc -l | awk '{ print $1 }')

if [ $RESULT -ne 1 ]
then
	echo "*** Unable to found default settings: ${RESULT} settings module(s) found!" >&2
	exit 1
fi

PYTHON_MODULE=$(echo $DEFAULT_SETTINGS | sed 's/\//./g' | sed 's/\.py$//')
msg "Default settings found: ${PYTHON_MODULE}"

sed -i "s/%DJANGO_SETTINGS_MODULE%/${PYTHON_MODULE}/" openshift/settings.py
msg "Python module openshift.settings updated!"
popd >/dev/null

# boot django database setup and static file collection
export DJANGO_SETTINGS_MODULE="openshift.settings"

msg "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py syncdb --noinput'"
python ${OPENSHIFT_REPO_DIR}manage.py syncdb --noinput

if python ${OPENSHIFT_REPO_DIR}manage.py | egrep '^ +startapp$' >/dev/null
then
	msg "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py migrate'"
	python ${OPENSHIFT_REPO_DIR}manage.py migrate
else
	msg "No migration to run (south not loaded)"
fi

if [ -d ${OPENSHIFT_DATA_DIR}static ]
then
	msg "Purging old static files..."
	rm -rf ${OPENSHIFT_DATA_DIR}static
fi

msg "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py collectstatic -l --noinput'"
python ${OPENSHIFT_REPO_DIR}manage.py collectstatic -l --noinput

