#!/bin/bash
# vim :set ts=4 sw=4 sts=4

set -e

source ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/common

VENV_VERSION=$(md5sum ${OPENSHIFT_REPO_DIR}requirements.txt | cut -d ' ' -f1)
VENV_BASE_DIR=${OPENSHIFT_DATA_DIR}virtualenvs/
VENV_APP_DIR=${VENV_BASE_DIR}${VENV_VERSION}

source ${VENV_APP_DIR}/bin/activate

if [ -f ${OPENSHIFT_DATA_DIR}.bash_profile ]
then
	source ${OPENSHIFT_DATA_DIR}.bash_profile
fi

export DJANGO_SETTINGS_MODULE="openshift.settings"

# gunicorn config
GUNICORN_BIN="python ${OPENSHIFT_REPO_DIR}manage.py run_gunicorn"
WORKERS=3
LOGFILE=${OPENSHIFT_DIY_LOG_DIR}gunicorn_out.log
ACCESS_LOGFILE=${OPENSHIFT_DIY_LOG_DIR}gunicorn_access.log
PIDFILE=${OPENSHIFT_RUNTIME_DIR}gunicorn.pid

# execute gunicorn daemon
${GUNICORN_BIN} unix:${OPENSHIFT_RUNTIME_DIR}gunicorn.socket \
	--daemon \
	--workers=${WORKERS} \
	--pid=${PIDFILE} \
	--log-file=${LOGFILE} \
	--access-logfile ${ACCESS_LOGFILE} \
	--log-level=info

${OPENSHIFT_RUNTIME_DIR}nginx/sbin/nginx
