#!/bin/bash
# vim :set ts=4 sw=4 sts=4

source ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/common

PIDFILE=${OPENSHIFT_RUN_DIR}gunicorn.pid

if [ -f $PIDFILE ]
then
	PID=$(cat $PIDFILE)
	rm $PIDFILE
	kill -15 $PID
fi

msg "Arrêt de nginx..."
kill -QUIT $(cat ${OPENSHIFT_RUN_DIR}/nginx.pid)

