#!/bin/bash
# vim :set ts=4 sw=4 sts=4

source ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/common

msg "Arrêt de nginx..."
nginx_pid_file=${OPENSHIFT_RUN_DIR}nginx.pid

if [ -f ${nginx_pid_file} ]
then
	pid=$(cat ${nginx_pid_file})

	if ps -p ${pid} >/dev/null
	then
		kill -15 ${pid}
	else
		rm ${nginx_pid_file}
	fi
fi

msg "Arrêt de gunicorn..."
gunicorn_pid_file=${OPENSHIFT_RUN_DIR}gunicorn.pid

if [ -f ${gunicorn_pid_file} ]
then
	pid=$(cat ${gunicorn_pid_file})

	if ps -p ${pid} >/dev/null
	then
		kill -15 ${pid}
	else
		rm ${gunicorn_pid_file}
	fi
fi

